SCHEMA

CREATE TABLE TEST(
    ID INT NOT NULL AUTO_INCREMENT,
    INPUT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RAW_DATA VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE CategoricalData(
	ID INT NOT NULL AUTO_INCREMENT,
    METAR VARCHAR(5) NOT NULL,
    LOCATION VARCHAR(4) NOT NULL,
    TIMESTAMP VARCHAR(7) NOT NULL,
    AUTO BOOLEAN,
    WIND VARCHAR(7) NOT NULL,
    WIND_VARIABILITY VARCHAR(7),
    CAVOK BOOLEAN,
    VISIBILITY INT,
    WEATHER VARCHAR(10),
    CLOUD VARCHAR(10),
    TempDew VARCHAR(5),
    QNH VARCHAR(6) NOT NULL,
    RAIN BOOLEAN,
    MajorWx BOOLEAN,
    PRIMARY KEY (ID)
);


CREATE VIEW CAVOKcounter AS
SELECT COUNT(*) AS CAVOK FROM categoricaldata
WHERE cavok = True;

CREATE VIEW MAJORWXcounter AS
SELECT COUNT(*) AS MAJORWX FROM categoricaldata
WHERE MAJORWX = True;